#include <stdio.h>
#include <stdlib.h>
#include<conio.h>

#include<windows.h>

int main()
{
system("color 0F");
printf("\n\n\n");
printf(".    .        .      .             . .     .        .          .          . \n");
Sleep(1000);
printf("         .                 .                    .                .          \n");
Sleep(1000);
printf("  .               A long time ago in a galaxy far, far away...   .           \n");
Sleep(1000);
printf("     .               .           .               .        .             . \n");
Sleep(1000);
printf("     .      .            .                 .                                . \n");
Sleep(1000);
printf(" .      .         .         .   . :::::+::::...      .          .         . \n");
Sleep(1000);
printf("     .         .      .    ..::.:::+++++:::+++++:+::.    .     . \n");
Sleep(1000);
printf("                        .:.  ..:+:..+|||+..::|+|+||++|:.             . \n");
Sleep(1000);
printf("            .   .    :::....:::::::::++||||O||O#OO|OOO|+|:.    . \n");
Sleep(1000);
printf(".      .      .    .:..:..::+||OO#|#|OOO+|O||####OO###O+:+|+               . \n");
Sleep(1000);
printf("                 .:...:+||O####O##||+|OO|||O#####O#O||OO|++||:     .    . \n");
Sleep(1000);
printf("  .             ..::||+++|+++++|+::|+++++O#O|OO|||+++..:OOOOO|+  .         . \n");
Sleep(1000);
printf("     .   .     +++||++:.:++:..+#|. ::::++|+++||++O##O+:.++|||#O+    . \n");
Sleep(1000);
printf(".           . ++++++++...:+:+:.:+: ::..+|OO++O|########|++++||##+            .\n");
Sleep(1000);
printf("  .       .  :::+++|O+||+::++++:::+:::+++::+|+O###########OO|:+OO       .  .\n");
Sleep(1000);
printf("     .       +:+++|OO+|||O:+:::::.. .||O#OOO||O||#@###@######:+|O|  . \n");
Sleep(1000);
printf(" .          ::+:++|+|O+|||++|++|:::+O#######O######O@############O \n");
Sleep(1000);
printf("          . ++++: .+OO###O++++++|OO++|O#@@@####@##################+         .\n");
Sleep(1000);
printf("      .     ::::::::::::::::::::++|O+..+#|O@@@@#@###O|O#O##@#OO####     .\n");
Sleep(1000);
printf(" .        . :. .:.:. .:.:.: +.::::::::  . +#:#@:#@@@#O||O#O@:###:#| .      .\n");
Sleep(1000);
printf("                           `. .:.:.:.:. . :.:.:%::%%%:::::%::::%:::\n");
Sleep(1000);
printf(".      .                                      `.:.:.:.:   :.:.:.:.  .   .\n");
Sleep(1000);
printf("           .                                                                .\n");
Sleep(1000);
printf("      .\n");
Sleep(1000);
printf(".          .                                                       .   .\n");
Sleep(1000);
printf("                                                                             .\n");
Sleep(1000);
printf("    .        .                                                           .\n");
Sleep(1000);
printf("    .     .                                                           .      .\n");
Sleep(1000);
printf("  .     .                                                        .\n");
Sleep(1000);
printf("              .   A terrible civil war burns throughout the  .        .     .\n");
Sleep(1000);
printf("                 galaxy: a rag-tag group of freedom fighters   .  .\n");
Sleep(1000);
printf("     .       .  has risen from beneath the dark shadow of the            .\n");
Sleep(1000);
printf(".        .     evil monster the Galactic Empire has become.                  .\n");
Sleep(1000);
printf("   .             Imperial  forces  have  instituted  a reign of   .      .\n");
Sleep(1000);
printf("             terror,  and every  weapon in its arsenal has  been \n");
Sleep(1000);
printf("          . turned upon the Rebels  and  their  allies:  tyranny, .   .\n");
Sleep(1000);
printf("   .       oppression, vast fleets, overwhelming armies, and fear.        .  .\n");
Sleep(1000);
printf(".      .  Fear  keeps  the  individual systems in line,  and is the   .\n");
Sleep(1000);
printf("         prime motivator of the New Order.             . \n");
Sleep(1000);
printf("    .      Outnumbered and outgunned,  the Rebellion burns across the   .    .\n");
Sleep(1000);
printf(".      vast reaches of space and a thousand-thousand worlds, with only     .\n");
Sleep(1000);
printf("    . their great courage - and the mystical power known as the Force -\n");
Sleep(1000);
printf("     flaming a fire of hope.                                    .\n");
Sleep(1000);
printf("       This is a  galaxy  of wondrous aliens,  bizarre monsters,  strange   .\n");
Sleep(1000);
printf(" . Droids, powerful weapons, great heroes, and terrible villains.  It is a\n");
Sleep(1000);
printf("  galaxy of fantastic worlds,  magical devices, vast fleets, awesome machi-  .\n");
Sleep(1000);
printf(" nery, terrible conflict, and unending hope.              .         .\n");
Sleep(1000);
printf(".        .          .    .    .            .            .                   .\n");
Sleep(1000);
printf("               .               ..       .       .   .             .\n");
Sleep(1000);
printf(" .      .     T h i s   i s   t h e   g a l a x y   o f   . . .             .\n");
Sleep(1000);
printf("                     .              .       .                    .      .\n");
Sleep(1000);
printf(".        .               .       .     .            .\n");
Sleep(1000);
printf("   .           .        .                     .        .            .\n");
Sleep(1000);
printf("             .               .    .          .              .   .         .\n");
Sleep(1000);

printf("\n\n\n\n\n\n\n\n\n");
printf("               _________________      ____         __________\n");
system("cls");
printf(" .       .    /                 |    /    \\    .  |          \\\n");
printf("     .       /    ______   _____| . /      \\      |    ___    |     .     .\n");
printf("             \\    \\    |   |       /   /\\   \\     |   |___>   |\n");
printf("           .  \    \\  |   |      /   /__\\   \\  . |         _/               .\n");
printf(" .     ________>    |  |   | .   /            \\   |   |\\    \_______    .\n");
printf("      |            /   |   |    /    ______    \\  |   | \\           |\n");
printf("      |___________/    |___|   /____/      \____\\ |___|  \_\_________|    .\n");
printf("  .     ____    __  . _____   ____      .  __________   .  _________\n");
printf("       \\    \\  /  \\  /    /  /    \\       |          \    /         |      .\n");
printf("        \\    \\/    \\/    /  /      \\      |    ___    |  /    ______|  .  \n");
printf("         \\              /  /   /\   \\ .   |   |___>   |  \\    \\           \n");
printf("   .      \\            /  /   /__\   \\    |         _/.   \\    \            +\n");
printf("           \\    /\\    /  /            \\   |   |\\    \______>    |   .\n");
printf("            \\  /  \\  /  /    ______    \\  |   | \\              /          .\n");
printf(" .       .   \\/    \\/  /____/      \\____\\ |___|  \\____________/  LS\n");
printf("                              .                                        .\n");
printf("     .                           .         .               .                 .\n");
printf("                .                                   .            .\n");
getch();
}
